{-|
Module      : Parser
Description : Parses the tokens into an AST

The parser gets fed the token generated by the lexer and generates an AST from them
  representing the program.
-}
module Banana.Syntax.Parser where
